project:
  type: default

format:
  revealjs:
    theme: [dark, singularity.scss]
    highlight-style: github-dark
    slide-number: c/t
    show-slide-number: speaker
    controls: true
    progress: true
    history: true
    transition: fade
    transition-speed: fast
    incremental: false
    center: false
    overview: true
    chalkboard: false
    menu: false
    hash-type: number
    embed-resources: false
    code-line-numbers: false
    width: 1280
    height: 720
    margin: 0.08
    mermaid:
      theme: dark
    bibliography: references.bib
